// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameInvoice = "invoices"

// Invoice mapped from table <invoices>
type Invoice struct {
	InvoicesID         int32     `gorm:"column:invoices_id;primaryKey;autoIncrement:true" json:"invoices_id"`
	SupplierID         int32     `gorm:"column:supplier_id;not null" json:"supplier_id"`
	InvoiceStartDate   time.Time `gorm:"column:invoice_start_date;not null" json:"invoice_start_date"`
	InvoiceDueDate     time.Time `gorm:"column:invoice_due_date;not null" json:"invoice_due_date"`
	InvoiceNumber      string    `gorm:"column:invoice_number;not null" json:"invoice_number"`
	InvoiceOrderNumber *string   `gorm:"column:invoice_order_number" json:"invoice_order_number"`
	InvoiceTitle       *string   `gorm:"column:invoice_title" json:"invoice_title"`
	InvoiceSubheading  *string   `gorm:"column:invoice_subheading" json:"invoice_subheading"`
	InvoiceLogo        *[]byte   `gorm:"column:invoice_logo" json:"invoice_logo"`
	InvoiceStatus      string    `gorm:"column:invoice_status;not null" json:"invoice_status"`
	InvoiceType        string    `gorm:"column:invoice_type;not null" json:"invoice_type"`
}

// TableName Invoice's table name
func (*Invoice) TableName() string {
	return TableNameInvoice
}
