// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameItemSell = "item_sells"

// ItemSell mapped from table <item_sells>
type ItemSell struct {
	ItemSellID   int32     `gorm:"column:item_sell_id;primaryKey;autoIncrement:false" json:"item_sell_id"`
	ItemID       int32     `gorm:"column:item_id;not null" json:"item_id"`
	InvoiceID    int32     `gorm:"column:invoice_id;not null" json:"invoice_id"`
	ItemSellTime time.Time `gorm:"column:item_sell_time;not null" json:"item_sell_time"`
}

// TableName ItemSell's table name
func (*ItemSell) TableName() string {
	return TableNameItemSell
}
